version: "3.5"

services:
########################### Infrastructure ######################################

  fuseki:
    image: saiye/fuseki:4.4.0
    hostname: fuseki
    restart: unless-stopped
    ports:
      - 3030:3030
    environment:
      - FUSEKI_DATASET_1=sm
      - ADMIN_PASSWORD=plasma
    volumes:
      - fuseki_data:/fuseki

  mariadb-sas:
    image: mariadb:latest
    hostname: mariadb-sas
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=plasma-sas
      - MYSQL_ROOT_PASSWORD=plasma
    volumes:
      - mariadb_sas:/var/lib/mysql
    healthcheck:
      test: bash -c "mariadb -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD  -e \"show databases;\""
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - 3307:3306

  mariadb-dms:
    image: mariadb:latest
    hostname: mariadb-dms
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=plasma-dms
      - MYSQL_ROOT_PASSWORD=plasma
    volumes:
      - mariadb_dms:/var/lib/mysql
    healthcheck:
      test: bash -c "mariadb -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD  -e \"show databases;\""
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - 3308:3306

  ########################### Service Infrastructure ######################################
  discovery:
    image: "plasma/discovery:${PLASMA_VERSION}"
    hostname: plasma-discovery-service
    restart: unless-stopped
    ports:
      - 8761:8761

  admin:
    image: "plasma/admin:${PLASMA_VERSION}"
    hostname: plasma-admin-service
    restart: unless-stopped
    depends_on:
      - discovery
    ports:
     - 8080:8080       

  gateway:
    image: "plasma/gateway:${PLASMA_VERSION}"
    hostname: plasma-gateway-service
    restart: unless-stopped
    depends_on:
      - discovery
    ports:
     - 8888:8888 
     
########################### Services ######################################
     
  kgs:
    image: "plasma/kgs:${PLASMA_VERSION}"
    hostname: plasma-kgs
    user: root
    restart: unless-stopped
    depends_on:
      - discovery
      - fuseki
    ports:
      - 8181:8181
    environment:
      - plasma.kgs.ontologies.folder=/var/ontologies
    volumes:
      - kgs_ontologies:/var/ontologies

  sas:
    image: "plasma/sas:${PLASMA_VERSION}"
    hostname: plasma-sas
    restart: unless-stopped
    depends_on:
      - discovery
      - mariadb-sas      
    ports:
     - 8189:8189   

  dms:
    image: "plasma/dms:${PLASMA_VERSION}"
    hostname: plasma-dms
    restart: unless-stopped
    volumes:
      - configs:/var/plasma/configs
    depends_on:
      - discovery
      - mariadb-dms
    ports:
      - 8186:8186
    environment:
      - plasma.dms.feature.recommendations.enabled=true

  dps:
    image: "plasma/dps:${PLASMA_VERSION}"
    hostname: plasma-dps
    user: root
    restart: unless-stopped
    depends_on:
      - discovery
    ports:
      - 8193:8193
    environment:
      - plasma.localstorage.directory=/var/plasma/localstorage
    volumes:
      - dps_storage:/var/plasma/localstorage

  srs:
    image: "plasma/srs:${PLASMA_VERSION}"
    hostname: plasma-srs
    restart: unless-stopped
    depends_on:
      - discovery   
    ports:
     - 8190:8190
    environment:
      - plasma.ars.labeling.url=http://plasma-ars-l-lm:8201/api/plasma-ars-l-lm
      - plasma.ars.modeling.url=
      - plasma.ars.refinement.url=

  frontend:
    build: ./frontend
    image: "plasma/ui:${PLASMA_VERSION}"
    hostname: plasma-ui
    restart: unless-stopped
    ports:
      - 80:80


volumes:
  fuseki_data:
  mariadb_sas:   
  mariadb_dms:
  configs:
  kgs_ontologies:
  dps_storage:
